const drugs = [
  { drugName: 'Adrenaline', type: 'range', dosemin: 0.01, dosemax: 1, unit: 'mcg/min', note: ' ' },
  { drugName: 'Adrenaline (1:1000) IM', type: 'single', dose: 0.01, unit: 'ml/dose', note: 'max 0.3 ml' },
  { drugName: 'Dopamine', type: 'range', dosemin: 5, dosemax: 20, unit: 'mcg/min', note: ' ' },
  { drugName: 'Norepinephrine', type: 'range', dosemin: 0.05, dosemax: 2, unit: 'mcg/min', note: ' ' },
  { drugName: 'Dobutamine', type: 'range', dosemin: 2, dosemax: 20, unit: 'mcg/min', note: ' ' },
  { drugName: 'Milrinone', type: 'range', dosemin: 0.25, dosemax: 0.75, unit: 'mcg/min', note: ' ' },
  { drugName: 'Lidocaine', type: 'range', dosemin: 20, dosemax: 50, unit: 'mcg/min', note: ' ' },
  { drugName: 'PGE1', type: 'range', dosemin: 0.05, dosemax: 0.1, unit: 'mcg/min', note: ' ' },
  { drugName: 'Vasopressin', type: 'range', dosemin: 0.5, dosemax: 2, unit: 'mcU/min', note: ' ' },
  { drugName: 'Amiodarone', type: 'single', dose: 5, unit: 'mg/dose', note: ' ' },
  { drugName: 'Adenosine', type: 'single', dose: 0.1, unit: 'mg/dose', note: 'max 6 - 12 mg ' },
  { drugName: 'Atropine', type: 'single', dose: 0.02, unit: 'mg/dose', note: 'max 0.5 mg ' },
  { drugName: '10%Calcium gluconate', type: 'single', dose: 1, unit: 'ml/dose', note: 'max 10 ml ' },
  { drugName: 'Dextrose', type: 'dextrose', dose: 1, unit: 'ml', note: ' ' },
  { drugName: '50% MgSO4', type: 'range', dosemin: 25, dosemax: 50, unit: 'mg/dose', note: ' ' },
  { drugName: '7.5% NaHCO3', type: 'single', dose: 1, unit: 'mEq/dose', note: 'max 50 ml ' },
  { drugName: 'hydrocortisone (Adrenal Insufficiency) ', type: 'nocalc', dose: '', unit: 'load 50 mg/m2 then 50 - 100 mg/m2/day IV q6 hr', note: ' ' },
  { drugName: 'hydrocortisone (Anaphylaxis) ', type: 'single', dose: 5, unit: 'mg/dose q6 hr', note: ' ' },
  { drugName: 'Naloxone', type: 'range', dosemin: 0.001, dosemax: 0.005, unit: 'mg/dose', note: 'max 0.1 mg ' },
  { drugName: '⸻⸻⸻', type: 'nocalc', dose: '', unit: ' ', note: ' ' },
  { drugName: 'Fentanyl', type: 'single', dose: 1, unit: 'mcg/dose', note: ' ' },
  { drugName: 'Fentanyl ', type: 'range', dosemin: 1, dosemax: 5, unit: 'mcg/hr', note: ' ' },
  { drugName: 'Midazolam (Dormicum)', type: 'range', dosemin: 0.05, dosemax: 0.1, unit: 'mg/dose', note: ' ' },
  { drugName: 'Nimbex', type: 'range', dosemin: 1, dosemax: 2, unit: 'mcg/min', note: ' ' },
  { drugName: 'Ketamine', type: 'range', dosemin: 0.25, dosemax: 1, unit: 'mg/dose', note: ' ' },
  { drugName: 'Morphine', type: 'range', dosemin: 0.05, dosemax: 0.1, unit: 'mg/dose', note: ' ' },
  { drugName: '⸻⸻⸻', type: 'nocalc', dose: '', unit: ' ', note: ' ' },
  { drugName: 'Furosemide', type: 'range', dosemin: 1, dosemax: 2, unit: 'mg/dose', note: ' ' },
  { drugName: 'Spinorolactone', type: 'range', dosemin: 1, dosemax: 3.3, unit: 'mg/day BID - QID', note: ' ' },
   { drugName: '⸻⸻⸻', type: 'nocalc', dose: '', unit: ' ', note: ' ' },
  { drugName: 'Bosentan', type: 'single', dose: 2, unit: 'mg/dose BID', note: ' ' },
  { drugName: 'Sildenafil', type: 'range', dosemin: 1, dosemax: 2, unit: 'mg/dose PO q6 hr', note: ' ' },
  { drugName: 'Prostaglandin I2', type: 'range', dosemin: 1, dosemax: 2.5, unit: 'mcg via nebulizer', note: ' ' },
  { drugName: 'Prostaglandin I2', type: 'range', dosemin: 1, dosemax: 10, unit: 'ng/min', note: ' ' },
  { drugName: '⸻⸻⸻', type: 'nocalc', dose: '', unit: ' ', note: ' ' },
  { drugName: 'Nicardipine', type: 'range', dosemin: 0.5, dosemax: 1, unit: 'mcg/min', note: 'max 4-5 mcg/kg/min ' },
  { drugName: 'Hydralazine', type: 'range', dosemin: 0.1, dosemax: 0.2, unit: 'mg/dose q4-6 hr', note: ' ' },
  { drugName: 'Enalapril', type: 'single', dose: 0.08, unit: 'mg/day', note: ' ' },
  { drugName: 'Nitroglycerine (NTG)', type: 'range', dosemin: 1, dosemax: 4, unit: 'mcg/min', note: ' ' },
];
export default drugs;